param(
  [Parameter(Mandatory = $true)][string]$Project,
  [string]$Lockfile = '',
  [switch]$NoProjectUpdate
)

$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'env.ps1')

function Resolve-OwnedPath {
  param(
    [Parameter(Mandatory = $true)][string]$Root,
    [Parameter(Mandatory = $true)][string]$Path
  )

  if ([IO.Path]::IsPathRooted($Path)) {
    throw "path must be relative to the project root: $Path"
  }

  $RootFull = [IO.Path]::GetFullPath($Root)
  $Candidate = [IO.Path]::GetFullPath((Join-Path $RootFull $Path))
  $Prefix = $RootFull.TrimEnd([IO.Path]::DirectorySeparatorChar, [IO.Path]::AltDirectorySeparatorChar) + [IO.Path]::DirectorySeparatorChar
  if (-not $Candidate.Equals($RootFull, [StringComparison]::OrdinalIgnoreCase) -and
      -not $Candidate.StartsWith($Prefix, [StringComparison]::OrdinalIgnoreCase)) {
    throw "path must stay inside project root: $Path"
  }
  return $Candidate
}

function Resolve-ProjectPython {
  param(
    [Parameter(Mandatory = $true)][string]$ProjectRoot,
    [string]$Python
  )

  if (-not $Python) {
    $Python = 'python'
  }

  if ([IO.Path]::IsPathRooted($Python) -and (Test-Path -LiteralPath $Python)) {
    return (Resolve-Path -LiteralPath $Python).Path
  }

  if (-not [IO.Path]::IsPathRooted($Python)) {
    $ProjectPython = Join-Path $ProjectRoot $Python
    if (Test-Path -LiteralPath $ProjectPython) {
      return (Resolve-Path -LiteralPath $ProjectPython).Path
    }
  }

  if ($Python -in @('python', 'python.exe', 'python3', 'python3.exe') -and
      $env:HVAC_STUDIO_PYTHON -and
      (Test-Path -LiteralPath $env:HVAC_STUDIO_PYTHON)) {
    return (Resolve-Path -LiteralPath $env:HVAC_STUDIO_PYTHON).Path
  }

  $Command = Get-Command $Python -ErrorAction SilentlyContinue
  if ($null -ne $Command) {
    return $Command.Source
  }

  throw "could not resolve project Python executable: $Python"
}

$ProjectPath = (Resolve-Path -LiteralPath $Project).Path
$ProjectRoot = Split-Path -Parent $ProjectPath
$ProjectJson = Get-Content -Raw -LiteralPath $ProjectPath | ConvertFrom-Json

if ($null -eq $ProjectJson.environment) {
  $ProjectJson | Add-Member -MemberType NoteProperty -Name environment -Value ([pscustomobject]@{})
}

$Environment = $ProjectJson.environment
$Python = Resolve-ProjectPython -ProjectRoot $ProjectRoot -Python $Environment.python

if (-not $Lockfile) {
  $Lockfile = [string]$Environment.lockfile
}
if (-not $Lockfile) {
  $Lockfile = 'requirements.lock.txt'
}

$LockfilePath = Resolve-OwnedPath -Root $ProjectRoot -Path $Lockfile
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $LockfilePath) | Out-Null

$FreezeLines = @()
if ($env:HVAC_STUDIO_UV -and (Test-Path -LiteralPath $env:HVAC_STUDIO_UV)) {
  $FreezeLines = & $env:HVAC_STUDIO_UV pip freeze --python $Python
  if ($LASTEXITCODE -ne 0) {
    throw "uv pip freeze failed with exit code $LASTEXITCODE"
  }
} else {
  $FreezeLines = & $Python -m pip freeze
  if ($LASTEXITCODE -ne 0) {
    throw "$Python -m pip freeze failed with exit code $LASTEXITCODE"
  }
}

$PythonVersion = (& $Python --version).Trim()
$Content = @(
  '# HVAC Studio project Python lockfile'
  '# Generated by scripts/dev/freeze-project-python.ps1'
  "# Python: $PythonVersion"
) + ($FreezeLines | Where-Object { $_ -and -not $_.StartsWith('Using Python ') })

$Content | Set-Content -LiteralPath $LockfilePath -Encoding UTF8

if (-not $NoProjectUpdate) {
  if ($null -eq $Environment.lockfile) {
    $Environment | Add-Member -MemberType NoteProperty -Name lockfile -Value $Lockfile
  } else {
    $Environment.lockfile = $Lockfile
  }
  $ProjectJson | ConvertTo-Json -Depth 20 | Set-Content -LiteralPath $ProjectPath -Encoding UTF8
}

Write-Host "project Python lockfile written: $LockfilePath"
Write-Output $LockfilePath
